Validate PostalCode has only numbers
Talentify/php-value-objects pull request #29
Opened 2021-04-30 19:48 UTC by vivianequinaia

2021-04-30 20:01 UTC, gnumoksha requested changes
add test case

2021-04-30 20:01 UTC, gnumoksha commented on src/Geography/Address/ByCountry/Us/ZipCode.php
> +        if (empty($value) || $characters != 5 && $characters != 9 && ctype_digit($value)) {
```suggestion
        if (empty($value) || ctype_digit($value) !== true || ($characters != 5 && $characters != 9)) {
```

2021-05-03 11:55 UTC, Joilson approved these changes

2021-05-03 11:57 UTC, roquerodrigo commented on src/Geography/Address/ByCountry/Us/ZipCode.php
> +        if (empty($value) || ctype_digit($changedValue) !== true || ($characters != 5 && $characters != 9)) {
Primeira vez na vida que vejo essa função 😆

2021-05-03 11:57 UTC, roquerodrigo approved these changes

2021-05-03 12:26 UTC, merged